// This will be auto-generated by Supabase CLI
export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          password_hash: string
          role: 'dev' | 'owner' | 'staff'
          company_id: string | null
          name: string
          is_active: boolean
          created_at: string
          updated_at: string
          created_by: string | null
        }
        Insert: {
          id?: string
          email: string
          password_hash: string
          role: 'dev' | 'owner' | 'staff'
          company_id?: string | null
          name: string
          is_active?: boolean
          created_at?: string
          updated_at?: string
          created_by?: string | null
        }
        Update: {
          id?: string
          email?: string
          password_hash?: string
          role?: 'dev' | 'owner' | 'staff'
          company_id?: string | null
          name?: string
          is_active?: boolean
          created_at?: string
          updated_at?: string
          created_by?: string | null
        }
      }
      companies: {
        Row: {
          id: string
          name: string
          subscription_plan_id: string
          is_active: boolean
          created_at: string
          updated_at: string
          created_by: string
        }
        Insert: {
          id?: string
          name: string
          subscription_plan_id: string
          is_active?: boolean
          created_at?: string
          updated_at?: string
          created_by: string
        }
        Update: {
          id?: string
          name?: string
          subscription_plan_id?: string
          is_active?: boolean
          created_at?: string
          updated_at?: string
          created_by?: string
        }
      }
      modules: {
        Row: {
          id: string
          name: string
          slug: string
          category: 'system' | 'company' | 'erp'
          description: string
          icon: string
          route_path: string
          is_active: boolean
          sort_order: number
        }
        Insert: {
          id?: string
          name: string
          slug: string
          category: 'system' | 'company' | 'erp'
          description: string
          icon: string
          route_path: string
          is_active?: boolean
          sort_order: number
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          category?: 'system' | 'company' | 'erp'
          description?: string
          icon?: string
          route_path?: string
          is_active?: boolean
          sort_order?: number
        }
      }
      module_permissions: {
        Row: {
          id: string
          user_id: string
          module_id: string
          can_read: boolean
          can_create: boolean
          can_update: boolean
          can_delete: boolean
          granted_at: string
          granted_by: string
        }
        Insert: {
          id?: string
          user_id: string
          module_id: string
          can_read?: boolean
          can_create?: boolean
          can_update?: boolean
          can_delete?: boolean
          granted_at?: string
          granted_by: string
        }
        Update: {
          id?: string
          user_id?: string
          module_id?: string
          can_read?: boolean
          can_create?: boolean
          can_update?: boolean
          can_delete?: boolean
          granted_at?: string
          granted_by?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']
export type InsertTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert']
export type UpdateTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update']
