import { Module } from '@/types/modules'

/**
 * Role-based module definitions
 * Centralized module configuration following DRY principle
 */

// ERP Modules (Staff - 12 modules)
export const ERP_MODULES: Module[] = [
  {
    id: 'erp-dashboard',
    name: 'Dashboard',
    icon: 'LayoutDashboard',
    category: 'erp',
    route_path: '/erp/dashboard',
    is_active: true,
    sort_order: 1,
    slug: 'dashboard',
    description: 'Overview of business metrics and activities',
  },
  {
    id: 'customers',
    name: 'Customers',
    icon: 'Users2',
    category: 'erp',
    route_path: '/erp/customers',
    is_active: true,
    sort_order: 2,
    slug: 'customers',
    description: 'Manage customer database and relationships',
  },
  {
    id: 'suppliers',
    name: 'Suppliers',
    icon: 'Truck',
    category: 'erp',
    route_path: '/erp/suppliers',
    is_active: true,
    sort_order: 3,
    slug: 'suppliers',
    description: 'Manage supplier database and vendor relationships',
  },
  {
    id: 'products',
    name: 'Products',
    icon: 'Package',
    category: 'erp',
    route_path: '/erp/products',
    is_active: true,
    sort_order: 4,
    slug: 'products',
    description: 'Manage product catalog and inventory items',
  },
  {
    id: 'inventory',
    name: 'Inventory',
    icon: 'Package',
    category: 'erp',
    route_path: '/erp/inventory',
    is_active: true,
    sort_order: 5,
    slug: 'inventory',
    description: 'Track stock levels and warehouse management',
  },
  {
    id: 'purchase-orders',
    name: 'Purchase Orders',
    icon: 'ShoppingCart',
    category: 'erp',
    route_path: '/erp/purchase-orders',
    is_active: true,
    sort_order: 6,
    slug: 'purchase-orders',
    description: 'Manage purchase orders from suppliers',
  },
  {
    id: 'sales-orders',
    name: 'Sales Orders',
    icon: 'TrendingUp',
    category: 'erp',
    route_path: '/erp/sales-orders',
    is_active: true,
    sort_order: 7,
    slug: 'sales-orders',
    description: 'Manage sales orders and customer orders',
  },
  {
    id: 'invoices',
    name: 'Invoices',
    icon: 'Receipt',
    category: 'erp',
    route_path: '/erp/invoices',
    is_active: true,
    sort_order: 8,
    slug: 'invoices',
    description: 'Create and manage customer invoices',
  },
  {
    id: 'payments',
    name: 'Payments',
    icon: 'CreditCard',
    category: 'erp',
    route_path: '/erp/payments',
    is_active: true,
    sort_order: 9,
    slug: 'payments',
    description: 'Track and manage payment transactions',
  },
  {
    id: 'warehouse',
    name: 'Warehouse',
    icon: 'Building2',
    category: 'erp',
    route_path: '/erp/warehouse',
    is_active: true,
    sort_order: 10,
    slug: 'warehouse',
    description: 'Warehouse management and stock locations',
  },
  {
    id: 'reporting',
    name: 'Reporting',
    icon: 'BarChart3',
    category: 'erp',
    route_path: '/erp/reporting',
    is_active: true,
    sort_order: 11,
    slug: 'reporting',
    description: 'Business reports and analytics',
  },
  {
    id: 'settings',
    name: 'Settings',
    icon: 'Settings',
    category: 'erp',
    route_path: '/erp/settings',
    is_active: true,
    sort_order: 12,
    slug: 'settings',
    description: 'ERP system configuration and preferences',
  },
]

// Company Modules (Owner - 4 modules)
export const COMPANY_MODULES: Module[] = [
  {
    id: 'company-dashboard',
    name: 'Dashboard',
    icon: 'LayoutDashboard',
    category: 'company',
    route_path: '/company/dashboard',
    is_active: true,
    sort_order: 1,
    slug: 'dashboard',
    description: 'Company Overview',
  },
  {
    id: 'subscription',
    name: 'Subscription & Billing',
    icon: 'Receipt',
    category: 'company',
    route_path: '/company/subscription',
    is_active: true,
    sort_order: 2,
    slug: 'subscription',
    description: 'View/manage subscription plan, payments, billing history',
  },
  {
    id: 'company-users',
    name: 'Employee Management',
    icon: 'UserCog',
    category: 'company',
    route_path: '/company/users',
    is_active: true,
    sort_order: 3,
    slug: 'users',
    description: 'Add/edit/remove employees, assign roles',
  },
  {
    id: 'company-reports',
    name: 'Company Data & Reporting',
    icon: 'BarChart3',
    category: 'company',
    route_path: '/company/reports',
    is_active: true,
    sort_order: 4,
    slug: 'reports',
    description: 'View company-wide reports (sales, inventory, finance)',
  },
]

// System Modules (Dev - 5 modules)
export const SYSTEM_MODULES: Module[] = [
  {
    id: 'system-dashboard',
    name: 'Dashboard',
    icon: 'LayoutDashboard',
    category: 'system',
    route_path: '/system/dashboard',
    is_active: true,
    sort_order: 1,
    slug: 'dashboard',
    description: 'System Overview',
  },
  {
    id: 'subscription-plans',
    name: 'Subscription Plan Management',
    icon: 'CreditCard',
    category: 'system',
    route_path: '/system/subscription-plans',
    is_active: true,
    sort_order: 2,
    slug: 'subscription-plans',
    description: 'Create, update, delete plans dengan pricing',
  },
  {
    id: 'companies',
    name: 'Company Management',
    icon: 'Building2',
    category: 'system',
    route_path: '/system/companies',
    is_active: true,
    sort_order: 3,
    slug: 'companies',
    description: 'Add/manage registered companies',
  },
  {
    id: 'system-users',
    name: 'Global User Management',
    icon: 'Users',
    category: 'system',
    route_path: '/system/users',
    is_active: true,
    sort_order: 4,
    slug: 'users',
    description: 'View all registered users across companies',
  },
  {
    id: 'monitoring',
    name: 'System Monitoring',
    icon: 'Activity',
    category: 'system',
    route_path: '/system/monitoring',
    is_active: true,
    sort_order: 5,
    slug: 'monitoring',
    description: 'View subscription status, usage analytics, system health',
  },
]
