import { Module } from '@/types/modules'

/**
 * Role-based module definitions
 * Centralized module configuration following DRY principle
 */

// ERP Modules (Staff - Dashboard + 10 feature modules from spec)
// Module 1 (Customers) and Module 2 (Suppliers) are included
// Module 3-12 follows the implementation plan
export const ERP_MODULES: Module[] = [
  {
    id: 'erp-dashboard',
    name: 'Dashboard',
    icon: 'LayoutDashboard',
    category: 'erp',
    route_path: '/erp/dashboard',
    is_active: true,
    sort_order: 1,
    slug: 'dashboard',
    description: 'Overview of business metrics and activities',
  },
  {
    id: 'customers',
    name: 'Customers',
    icon: 'Users2',
    category: 'erp',
    route_path: '/erp/customers',
    is_active: true,
    sort_order: 2,
    slug: 'customers',
    description: 'Customer database management (Module 1)',
  },
  {
    id: 'suppliers',
    name: 'Suppliers',
    icon: 'Truck',
    category: 'erp',
    route_path: '/erp/suppliers',
    is_active: true,
    sort_order: 3,
    slug: 'suppliers',
    description: 'Supplier and vendor management (Module 2)',
  },
  {
    id: 'inventory',
    name: 'Inventory',
    icon: 'Package',
    category: 'erp',
    route_path: '/erp/inventory',
    is_active: true,
    sort_order: 4,
    slug: 'inventory',
    description: 'Products, stock, warehouse management (Module 3)',
  },
  {
    id: 'promotions',
    name: 'Promotions',
    icon: 'Percent',
    category: 'erp',
    route_path: '/erp/promotions',
    is_active: true,
    sort_order: 5,
    slug: 'promotions',
    description: 'Discount and promotion campaigns (Module 4)',
  },
  {
    id: 'pos',
    name: 'POS (Cashier)',
    icon: 'ShoppingCart',
    category: 'erp',
    route_path: '/erp/pos',
    is_active: true,
    sort_order: 6,
    slug: 'pos',
    description: 'Point of Sale transactions (Module 5)',
  },
  {
    id: 'sales',
    name: 'Sales',
    icon: 'TrendingUp',
    category: 'erp',
    route_path: '/erp/sales',
    is_active: true,
    sort_order: 7,
    slug: 'sales',
    description: 'Sales orders and invoicing (Module 6)',
  },
  {
    id: 'purchasing',
    name: 'Purchasing',
    icon: 'ShoppingCart',
    category: 'erp',
    route_path: '/erp/purchasing',
    is_active: true,
    sort_order: 8,
    slug: 'purchasing',
    description: 'Purchase orders and supplier invoices (Module 7)',
  },
  {
    id: 'hr',
    name: 'HR (Employee)',
    icon: 'UserCheck',
    category: 'erp',
    route_path: '/erp/hr',
    is_active: true,
    sort_order: 9,
    slug: 'hr',
    description: 'Employee management and HR (Module 8)',
  },
  {
    id: 'salesman',
    name: 'Salesman',
    icon: 'User',
    category: 'erp',
    route_path: '/erp/salesman',
    is_active: true,
    sort_order: 10,
    slug: 'salesman',
    description: 'Salesman tracking and commission (Module 9)',
  },
  {
    id: 'vehicles',
    name: 'Vehicles',
    icon: 'Truck',
    category: 'erp',
    route_path: '/erp/vehicles',
    is_active: true,
    sort_order: 11,
    slug: 'vehicles',
    description: 'Vehicle and delivery management (Module 10)',
  },
  {
    id: 'finance',
    name: 'Finance',
    icon: 'Calculator',
    category: 'erp',
    route_path: '/erp/finance',
    is_active: true,
    sort_order: 12,
    slug: 'finance',
    description: 'Financial reports and accounting (Module 11)',
  },
]

// Company Modules (Owner - 4 modules)
export const COMPANY_MODULES: Module[] = [
  {
    id: 'company-dashboard',
    name: 'Dashboard',
    icon: 'LayoutDashboard',
    category: 'company',
    route_path: '/company/dashboard',
    is_active: true,
    sort_order: 1,
    slug: 'dashboard',
    description: 'Company Overview',
  },
  {
    id: 'subscription',
    name: 'Subscription & Billing',
    icon: 'Receipt',
    category: 'company',
    route_path: '/company/subscription',
    is_active: true,
    sort_order: 2,
    slug: 'subscription',
    description: 'View/manage subscription plan, payments, billing history',
  },
  {
    id: 'company-users',
    name: 'Employee Management',
    icon: 'UserCog',
    category: 'company',
    route_path: '/company/users',
    is_active: true,
    sort_order: 3,
    slug: 'users',
    description: 'Add/edit/remove employees, assign roles',
  },
  {
    id: 'company-reports',
    name: 'Company Data & Reporting',
    icon: 'BarChart3',
    category: 'company',
    route_path: '/company/reports',
    is_active: true,
    sort_order: 4,
    slug: 'reports',
    description: 'View company-wide reports (sales, inventory, finance)',
  },
]

// System Modules (Dev - 5 modules)
export const SYSTEM_MODULES: Module[] = [
  {
    id: 'system-dashboard',
    name: 'Dashboard',
    icon: 'LayoutDashboard',
    category: 'system',
    route_path: '/system/dashboard',
    is_active: true,
    sort_order: 1,
    slug: 'dashboard',
    description: 'System Overview',
  },
  {
    id: 'subscription-plans',
    name: 'Subscription Plan Management',
    icon: 'CreditCard',
    category: 'system',
    route_path: '/system/subscription-plans',
    is_active: true,
    sort_order: 2,
    slug: 'subscription-plans',
    description: 'Create, update, delete plans dengan pricing',
  },
  {
    id: 'companies',
    name: 'Company Management',
    icon: 'Building2',
    category: 'system',
    route_path: '/system/companies',
    is_active: true,
    sort_order: 3,
    slug: 'companies',
    description: 'Add/manage registered companies',
  },
  {
    id: 'system-users',
    name: 'Global User Management',
    icon: 'Users',
    category: 'system',
    route_path: '/system/users',
    is_active: true,
    sort_order: 4,
    slug: 'users',
    description: 'View all registered users across companies',
  },
  {
    id: 'monitoring',
    name: 'System Monitoring',
    icon: 'Activity',
    category: 'system',
    route_path: '/system/monitoring',
    is_active: true,
    sort_order: 5,
    slug: 'monitoring',
    description: 'View subscription status, usage analytics, system health',
  },
]
